options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/kuberai', '.']

  # Step 2: Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/kuberai']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run',
        'deploy',
        'kuberai',
        '--image',
        'gcr.io/$PROJECT_ID/kuberai',
        '--region',
        'asia-south1',
        '--platform',
        'managed',
        '--memory',
        '2Gi',
        '--allow-unauthenticated',
        '--set-env-vars',
        'TOGETHER_API_KEY=${_TOGETHER_API_KEY},HUGGINGFACEHUB_API_TOKEN=${_HUGGINGFACEHUB_API_TOKEN}'
      ]

images:
  - 'gcr.io/$PROJECT_ID/kuberai'
